[package]
name = "parallel_computing_lab5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
[dependencies.ws-tokio]
path = "libs/ws-tokio"

[dependencies]
tokio = { version = "1", features = ["full"] }

